# DIRECTORY PARAMETER
set PROJECT_ROOT ./..
set SOURCE_ROOT ./..
set SNAPSHOT_ROOT ./snapshot_xsim

# PROJECT PARAMETER 
set DEVICE xc7a35tcpg236-1
#FLOW PARAMETERS 
set IP_GENERATION "NO"


source -notrace sim.tcl